on:
  push:
    branches:
      - '**'
name: lint
jobs:
  dipull:
    name: dipull
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.13.1]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install bun and Lint Test
        run: |
          curl -fsSL https://bun.sh/install | bash
          export PATH=$HOME/.bun/bin:$PATH  # Bun 설치 후 경로 설정
          cd dipull
          bun install
          bun run lint
  dipull-auth:
    name: dipull-auth
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.13.1]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install bun and Lint Test
        run: |
          curl -fsSL https://bun.sh/install | bash
          export PATH=$HOME/.bun/bin:$PATH  # Bun 설치 후 경로 설정
          cd dipull-auth
          bun install
          bun run lint
